### ISSUE TITLE
Target of netcore does not allow to be used in full framework...

### ISSUE THREAD

**Issue by joebuys** [EduSource/QuickBooks.Net#1]
I wanted to use your API wrapper in a full .net framework implementation.  However, because you targeted .netcore specifically, it does not allow to be used in a full environment.  Did you mean to target netstandard instead?

Is there a reason this could not run on a full .net framework (such as 4.6.x?)

**Comment by benaduggan** [comment]
Hey @joebuys, that's a good question. I'm not familiar with using netstandard, so I'm not sure if there would be a reason it couldn't run on full .net. We'll take a look into if there would be any compatibility issues with targeting that instead. 

I'm not sure about the timeline to fix that though, so if you want to submit a PR with it working, that would also be helpful!

**Comment by joebuys** [comment]
I'd be happy to help - although I have never done any NuGet package development.  So I am at a bit of a loss from where to get this building and tested.
But, from what I found in other threads, you want to change the netcore dependancy as they discuss in this thread:  https://github.com/aspnet/Home/issues/1618
By targeting NetStandard, you can allow both netcore and full netframework to use your project.

**Comment by andrew-smith3** [comment]
I took a look at this to see what version of .Net Standard we could use and it seems our only obstacle is the oauth-dotnetcore library. It targets .net standard 1.6 which is not supported by .net 4.6.  If we could find an alternative or see if oauth-dotnetcore could target down a few versions, I think we could target .net standard 1.4 or 1.3.

**Comment by ryandanthony** [comment]
@joebuys  can you look at the most recent version? your issue should be fixed now.
