### ISSUE TITLE
Nuget Quickbooks.Net package is referencing Quickbooks.Net.Data 1.0.0 instead of most recent version

### ISSUE THREAD

**Issue by rszemplinski** [EduSource/QuickBooks.Net#7]
Basically what the title states...

Have absolutely no idea on how to fix this issue.

**Comment by ryandanthony** [comment]
Let me look into it. Pretty sure  I know how to fix.

**Comment by ryandanthony** [comment]
Don't think that fixed it.

**Comment by rszemplinski** [comment]
yeah, unfortunately it didn't :(

**Comment by rszemplinski** [comment]
Do we have any more ideas?

**Comment by ryandanthony** [comment]
yes. looking at it now... I have used this exact methodology successfully before. But not with appveyor..

**Comment by ryandanthony** [comment]
ok that last one did it. 
https://ci.appveyor.com/project/benaduggan/quickbooks-net/build/1.0.42
